name: user_locations
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.5
  #  firebase_core: ^2.15.0
  #  cloud_firestore: ^4.8.3
  #  firebase_messaging: ^14.6.5
  #  firebase_auth: ^4.7.1
  #  firebase_storage: ^11.2.5
  flutter_local_notifications: ^15.1.0+1
  cached_network_image: ^3.2.3
  shared_preferences:
  flutter_slidable: ^3.0.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  zoom_tap_animation: ^1.1.0
  image_picker: ^1.0.1
  provider: ^6.0.5
  sqflite: ^2.3.0
  dio: ^5.3.2
  google_maps_flutter: ^2.4.0
  lottie:
  change_app_package_name: ^1.1.0
  location: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter



  build_runner: ^2.4.6


flutter:
  uses-material-design: true


  assets:
    - assets/images/
